### ISSUE TITLE
Constant reboot

### ISSUE THREAD

**Issue by rvdgaag** [MiGoller/ioBroker.life360#48] opened 2021-11-16 19:50 UTC
Life360 is constantly rebooting

**Versions:**  
 - Adapter version: 0.2.16
 - JS-Controller version: 3.3.18
 - Node version: v12.22.7
 - Operating system: 

Here is the log file:

life360.0 | 2021-11-16 20:41:42.769 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
-- | -- | -- | --
life360.0 | 2021-11-16 20:41:42.767 | info | terminating
life360.0 | 2021-11-16 20:41:42.766 | info | cleaned everything up...
life360.0 | 2021-11-16 20:41:42.765 | debug | Auth tokens deleted.
life360.0 | 2021-11-16 20:41:42.764 | info | Disabled polling.
life360.0 | 2021-11-16 20:41:42.759 | error | Cannot read property 'val' of null
life360.0 | 2021-11-16 20:41:42.758 | error | TypeError: Cannot read property 'val' of null at publishCirclePlaces (/opt/iobroker/node_modules/iobroker.life360/lib/life360DbConnector.js:833:99)
life360.0 | 2021-11-16 20:41:42.757 | error | unhandled promise rejection: Cannot read property 'val' of null
life360.0 | 2021-11-16 20:41:42.756 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
life360.0 | 2021-11-16 20:41:42.631 | debug | Life360 cloud data processed.
life360.0 | 2021-11-16 20:41:42.631 | debug | Published 2 circle(s) to ioBroker.
life360.0 | 2021-11-16 20:41:42.591 | debug | Published 0 MyPlaces to ioBroker.
life360.0 | 2021-11-16 20:41:42.557 | debug | Pushing cloud_data to callback function
life360.0 | 2021-11-16 20:41:42.556 | warn | No places found!
life360.0 | 2021-11-16 20:41:42.109 | debug | Polling Life360 places ... try #6
life360.0 | 2021-11-16 20:41:41.674 | debug | Polling Life360 places ... try #5
life360.0 | 2021-11-16 20:41:41.251 | debug | Polling Life360 places ... try #4
life360.0 | 2021-11-16 20:41:40.828 | debug | Polling Life360 places ... try #3
life360.0 | 2021-11-16 20:41:40.405 | debug | Polling Life360 places ... try #2
life360.0 | 2021-11-16 20:41:39.981 | debug | Polling Life360 places ... try #1
life360.0 | 2021-11-16 20:41:39.502 | debug | Polling Life360 members ... try #1
life360.0 | 2021-11-16 20:41:39.053 | debug | Polling Life360 places ... try #1
life360.0 | 2021-11-16 20:41:38.556 | debug | Polling Life360 members ... try #1
life360.0 | 2021-11-16 20:41:38.099 | debug | Polling Life360 circles... try #1
life360.0 | 2021-11-16 20:41:38.097 | info | Connected to Life360 cloud services.
life360.0 | 2021-11-16 20:41:38.091 | debug | Saved auth tokens.
life360.0 | 2021-11-16 20:41:38.090 | debug | Logged in as user: rvdgaag@mac.com, phone: .

life360.0 | 2021-11-16 20:41:42.769 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
-- | -- | -- | --
life360.0 | 2021-11-16 20:41:42.767 | info | terminating
life360.0 | 2021-11-16 20:41:42.766 | info | cleaned everything up...
life360.0 | 2021-11-16 20:41:42.765 | debug | Auth tokens deleted.
life360.0 | 2021-11-16 20:41:42.764 | info | Disabled polling.
life360.0 | 2021-11-16 20:41:42.759 | error | Cannot read property 'val' of null
life360.0 | 2021-11-16 20:41:42.758 | error | TypeError: Cannot read property 'val' of null at publishCirclePlaces (/opt/iobroker/node_modules/iobroker.life360/lib/life360DbConnector.js:833:99)
life360.0 | 2021-11-16 20:41:42.757 | error | unhandled promise rejection: Cannot read property 'val' of null
life360.0 | 2021-11-16 20:41:42.756 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
life360.0 | 2021-11-16 20:41:42.631 | debug | Life360 cloud data processed.
life360.0 | 2021-11-16 20:41:42.631 | debug | Published 2 circle(s) to ioBroker.
life360.0 | 2021-11-16 20:41:42.591 | debug | Published 0 MyPlaces to ioBroker.
life360.0 | 2021-11-16 20:41:42.557 | debug | Pushing cloud_data to callback function
life360.0 | 2021-11-16 20:41:42.556 | warn | No places found!
life360.0 | 2021-11-16 20:41:42.109 | debug | Polling Life360 places ... try #6
life360.0 | 2021-11-16 20:41:41.674 | debug | Polling Life360 places ... try #5
life360.0 | 2021-11-16 20:41:41.251 | debug | Polling Life360 places ... try #4
life360.0 | 2021-11-16 20:41:40.828 | debug | Polling Life360 places ... try #3
life360.0 | 2021-11-16 20:41:40.405 | debug | Polling Life360 places ... try #2
life360.0 | 2021-11-16 20:41:39.981 | debug | Polling Life360 places ... try #1
life360.0 | 2021-11-16 20:41:39.502 | debug | Polling Life360 members ... try #1
life360.0 | 2021-11-16 20:41:39.053 | debug | Polling Life360 places ... try #1
life360.0 | 2021-11-16 20:41:38.556 | debug | Polling Life360 members ... try #1
life360.0 | 2021-11-16 20:41:38.099 | debug | Polling Life360 circles... try #1
life360.0 | 2021-11-16 20:41:38.097 | info | Connected to Life360 cloud services.
life360.0 | 2021-11-16 20:41:38.091 | debug | Saved auth tokens.
life360.0 | 2021-11-16 20:41:38.090 | debug | Logged in as user: rvdgaag@mac.com, phone: .

**Comment by MiGoller** [comment] 2021-11-16 20:37
Hey @rvdgaag . I'll have a look at it. Did you upgrade the adapter from a prior version, or did you set up the adapter the first time?

**Comment by rvdgaag** [comment] 2021-11-16 20:40
I tried a raspi with a clean install after I upgraded from a previous version on a intel nuc , both behave the same (also the previous version by the way).

**Comment by MiGoller** [comment] 2021-11-16 20:42
Ah, ok, thx for your feedback. I'll have a look for the reason the adapter crashes.

**Comment by MiGoller** [comment] 2021-11-16 20:58
If I get you right, the adapter is still not working, right? In that case I'd like to clean up any circle entries at `life360.0.circles`. The `circles` node should be empty.
![image](https://user-images.githubusercontent.com/1272642/142064267-63709f7f-b727-4126-95c8-0899f7de8326.png)

Please stop the Life360 adapter instance before cleaning up the circles. Restart the adapter right after the cleanup. Please let me know, if the adapter starts up and publishes the circles, please.

**Comment by MiGoller** [comment] 2021-11-16 21:15
Looks like this is a duplicate of #41 . Will be fixed in v0.2.17. Hopefully the cleanup will does the trick as a workaround.

**Comment by rvdgaag** [comment] 2021-11-16 21:47
Cleanup worked, circles are published again. I'll let you know if this workaround is stable.

**Comment by MiGoller** [comment] 2021-11-16 21:50
I'm glad to hear about that. Good luck. This should be fixed with release v0.2.17 finally.

I'll let you know when I'll have released the new version in a few days.

KR, MiGoller

**Comment by MiGoller** [comment] 2022-03-06 13:35
Waiting for feedback about v0.2.17

**Closed** 2022-11-11 21:20 UTC
Labels: bug
